---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url: 
sections:
- type: directory
  path: content/pages
  label: Pages
  create: documents
  match: "**/*.md"
  templates:
  - single-page
- type: directory
  path: content/proyectos
  label: Proyectos
  create: documents
  match: "**/*.md"
  templates:
  - proyecto
- type: directory
  path: content/cursos
  label: Cursos
  create: documents
  match: "**/*.md"
  templates:
  - curso
- type: document
  path: data/theme.json
  label: Theme config
- type: document
  path: README.md
  label: Status
  match: "**/*"
  read_only: true
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:filename:"
build:
  preview_output_directory: dist
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
