---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url: 
sections:
- type: directory
  path: content/proyectos
  label: Proyectos
  create: documents
  match: "**/*.md"
  templates:
  - proyecto
- type: directory
  path: content/cursos
  label: Cursos
  create: documents
  match: "**/*.md"
  templates:
  - curso
- type: directory
  path: content/notas
  label: Notas
  create: all
  match: "**/*.md"
  templates:
  - nota
- type: directory
  path: content
  label: Bazar
  create: all
  match: bazar/obras/**/*.md
  templates:
  - bazar-obra
- type: directory
  path: content/pages
  label: Single Pages
  create: all
  match: "**/*.md"
  templates:
  - single-page
- type: document
  path: data/theme.json
  label: Config
- type: document
  path: README.md
  label: Status
  read_only: true
upload_dir: ''
public_path: https://res.cloudinary.com/freezer/c_limit,w_1280,h_920
front_matter_path: ''
use_front_matter_path: true
file_template: ":year:/:filename:"
build:
  preview_output_directory: dist
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
