---
label: Config
hide_body: true
fields:
- type: text
  name: site_name
  label: Site name
- type: textarea
  name: site_description
  label: Site description
- name: footer
  label: Footer text
  type: text
  hidden: false
  default: ''
- type: boolean
  name: dark_mode
  label: Dark mode
- name: menu
  type: field_group_list
  fields:
  - name: name
    type: text
    config:
      required: false
    label: Name
  - name: url
    type: text
    config:
      required: false
    label: Url
  config:
    min: 
    max: 
    labelField: 
  label: Menu
- name: tv_playlist
  type: text
  config:
    required: false
  label: TV playlist
  description: El <strong>ID</strong> de la playlist. Por ejemplo, https://www.youtube.com/watch?v=rtgGol-I4gA&amp;list=<strong>PL12DC9A161D8DC5DC</strong>&amp;index=1
- type: textarea
  name: banner
  label: Banner
  description: El bannerrrrr
  hidden: false
  default: ""
  config:
      wysiwyg: true
pages:
- data/config.json
